<template>
  <table class="kind" border="1" >
    <thead>
    <td>目</td>
    <td>科</td>
    <td>属</td>
    <td width="450px">种</td>
    </thead>
    <tbody>
    <tr>
      <td>曲颈龟亚目</td>
      <td>两抓鳖科</td>
      <td>两抓鳖属</td>
      <td>猪鼻龟</td>
    </tr>
    <tr>
      <td></td>
      <td>海龟科</td>
      <td>蠵龟属</td>
      <td>
        <span>大西洋蠵龟</span>
        <span>太平洋蠵龟</span>
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>海龟属</td>
      <td>
        <span>太平洋绿海龟</span>
        <span>平背海龟</span>
        <span>绿海龟</span>
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>玳瑁属</td>
      <td>
        <span>玳瑁</span>
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>丽龟属</td>
      <td>
        <span>肯普氏丽龟</span>
        <span>太平洋丽龟</span>
      </td>
    </tr>
    <tr>
      <td></td>
      <td>棱皮龟科</td>
      <td>棱皮龟属</td>
      <td>
        <span>棱皮龟</span>
      </td>
    </tr>
    <tr>
      <td></td>
      <td>鳄龟科</td>
      <td>真鳄龟属</td>
      <td>
        <span>真鳄龟（大鳄龟）</span>
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>拟鳄龟属</td>
      <td>
        <span>北美拟鳄龟（小鳄龟）</span>
        <span>南美拟鳄龟</span>
        <span>中美拟鳄龟</span>
        <span>佛洲拟鳄龟</span>
      </td>
    </tr>
    <tr>
      <td></td>
      <td>泥龟科</td>
      <td>泥龟属</td>
      <td>
        <span>北中美洲河龟</span>
      </td>
    </tr>
    <tr>
      <td></td>
      <td>龟科</td>
      <td>安南龟属</td>
      <td>
        <span>安南龟</span>
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>潮龟属</td>
      <td>
        <span>巴达库尔龟</span>
      </td>
    </tr>
    <tr>
      <td></td>
      <td>地龟科</td>
      <td>咸水龟属</td>
      <td>
        <span>咸水泥彩龟</span>
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>乌龟属</td>
      <td>
        <span>黑颈乌龟</span>
        <span>大乌龟</span>
        <span>乌龟</span>
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>闭壳龟属</td>
      <td>
        <span>金头闭壳龟</span>
        <span>百色闭壳龟</span>
        <span>潘氏闭壳龟</span>
        <span>三线闭壳龟</span>
        <span>云南闭壳龟</span>
        <span>周氏闭壳龟</span>
        <span>黄缘闭壳龟（黄缘盒龟）</span>
        <span>琉球黄缘闭壳龟</span>
        <span>南中国黄缘闭壳龟</span>
        <span>黄额闭壳龟</span>
        <span>黒腹黄额闭壳龟</span>
        <span>海南黄额闭壳龟</span>
        <span>锯齿黄额闭壳龟</span>
        <span>图画黄额闭壳龟</span>
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>齿缘摄属</td>
      <td>
        <span>齿缘摄龟</span>
        <span>条颈摄龟</span>
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>地龟属</td>
      <td>
        <span>日本地龟</span>
        <span>地龟</span>
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>池龟属</td>
      <td>
        <span>哈密顿氏龟（斑点池龟）</span>
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>草龟属</td>
      <td>
        <span>冠背龟</span>
        <span>印度冠背龟</span>
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>东方龟属</td>
      <td>
        <p>缅甸山龟</p>
        <p>亚洲巨龟</p>
        <p>菲律宾池龟</p>
        <p>蔗林龟</p>
        <p>刺山龟（太阳龟）</p>
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>庙龟属</td>
      <td>
        <p>黄头庙龟属</p>
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>棱背龟属</td>
      <td>
        <p>巨型棱背龟</p>
        <p>红冠棱背龟</p>
        <p>史密斯棱背龟</p>
        <p>白足棱背龟</p>
        <p>阿萨姆棱背龟</p>
        <p>印度棱背龟</p>
        <p>缅甸棱背龟</p>
        <p>粉红圈锯背龟</p>
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>马来龟属</td>
      <td>
        <p>马来食螺龟</p>
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td>拟水龟属</td>
      <td>
        <p>里海泽龟</p>
        <p>希腊泽龟</p>
        <p>艾氏拟水龟</p>
        <p>日本石龟</p>
        <p>黄喉拟水龟</p>
        <p>腊戌拟水龟</p>
      </td>
    </tr>
    </tbody>
  </table>
</template>
export default {
  data:{
    return{
    }
  }
}

<style scoped lang="scss">
    .kind{
      width:100%;
      text-align: center;
      border-collapse: collapse;
      background:#fff;
    }

</style>
